language: java
jdk: oraclejdk8
sudo: required
dist: trusty
services:
- docker
before_install:
- chmod +x mvnw
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=latest
- export IMAGE_NAME=r3ap3rpy/bvassignment
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME
env:
  global:
  - secure: a+Vjt+yIucWTPbVI6MBoKyYPtu7wL0Rdnwzbq0An+ISqcboU7+Iod3wz5ZqXjKBC+wtPLpA4v9QMxBydZdbE31kw46PqdKUxpcqDw9v6crzaGmipccTaeIsrxBoQSEYaeHTIbZAloCIfYyofgS/VgFVrA2YBapqDs5hf+783eBc3qaJk8SiANH+DhSP0gL2fd0aGyG4Ty0VheexFVcuwZVjrv9PRVkZqRAcLhmxu1lYxSoI90Dt+oQp7RyuXMctYt4LHPd0wNnXmrlIYEMc5gU/E/LtLBeXKuKT8CnMZF6w1G9eHAN9IaWKRCY4SyFvgzAN0AydC2+qSdLLTmOo7HOf5m3zAuO4zdNtxhiGdomjjIi8zGyLSLRPGmdvG8oOCu8vDZ1zyJ9ClFQvSozJ2TdUn+87qdSLskXp3AFmrxTmyspRYomdRcmB5JffoEgZFs/eZySyX/9uKMwAGkEz+CrIH+/dXphrZ54/T7KepgJVVaXIBwCduRknBVVi5K5En0JkZPnx84l4hIHyH6v7Ac0OaYAbEk0cq8x5I+h/0JZS3j9SS+PX0h/ISh06/seDlIwfuZTKz2keSUt/ZrvDkc/1M4zB9vg4Ize8FF8DaH10pEt+6LOlM/6OAWykzOzijDbH/l0eHJyqnEqfccdBJo00WibCEEwJQyAzteEawWWs=
  - secure: wB3naCZicFIxnl7pX3eVsJfBv1uev6h2Kcr88Qyw0jKzRKALH+nv4rjSEaWil0nDK9kJ6Cru19mdLm7CL6Bc2KbtlvA8MmMFivpvFrJr8hROcwnSewynx8M4HbHLowYgBXsicBeZNQFPUdnoCaVy9aN1tZkYB2hh9jNbdiAAV1y9SbvkaouxWa+ck9Ly5Bnh6llt1IhpQz6zqOinM3u1Z6Pll/nFDrnvR63Vyf1NHCdFZFnKa350zLuy4vXRMIS02/sLu4/jfIFdkrs/QFL35FjTEJPmXBtN4qV71mGw9ilJSf+0I+D/pRuQ+knOldfR/WN4yPR/HDQe5YMjGwMHituxd5FxNaZeu7ttHXhsdmbDzVhXecMoBH6DUDWVrA/xnbFedfNz5hjUWpwe3RlRL5zInUfY2wEIRpIjDPG0naRTTO2++qw2pvTvXJEot4ZREtJiSp7HLDzuajFaJdXEqOB7slskDhG3Wr5IMteWFAFOM5Y8Qvg21JM98vaf6Jaofu2yptxT4Ke1GW6aBaRTA+qALmTtpPIYtUSXEwU7CKmdXVm3qRivodhntFbcsnmy/qYV7Ut4v5vKEhqiJP6smXNS9jzMvs4x7vYspNGjOzmK19e0scZoASp1I//QeEA71IoFFPoA42MIW9fRQGs4Tc0LauTARJluCujG2evjUMU=
