language: java
jdk: oraclejdk8
os: linux
dist: trusty
services:
- docker
before_install:
- chmod +x mvnw
- ./mvnw clean install -B
after_success:
- echo $DOCKER_PASSWORD
- echo $DOCKER_USERNAME
- echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
- pwd
- ls -l ./target
- docker build  -t bvassignment .
- docker tag bvassignment $DOCKER_USERNAME/bvassignment:latest
- docker push $DOCKER_USERNAME/bvassignment:latest
- docker images
