language: java
jdk: oraclejdk8
os: linux
dist: trusty
services:
- docker
before_install:
- chmod +x mvnw
after_success:
- echo $DOCKER_PASSWORD
- echo $DOCKER_USERNAME
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
- ls -l
- docker build -t bvassignment .
- docker tag bvassignment $DOCKER_USERNAME/bvassignment:latest
- docker push $DOCKER_USERNAME/bvassignment:latest
- docker images
env:
  global:
  - secure: MQknrDybipkJ1pOqxmW5Hn/nR+/bvz1zjG9Hg3DXQRisls55QoigIpBBi6mC6yWFgn8PdXZUeRJHq/iwiXAf4f4LDe3gP13tN7aG4+Fctn1J+fs1lzhWh2tgy1CHcuF+MZ5lbqBeXpL8QUh5QyyjsyHCo9RBJEF5A+vNZRDUPQ7fmI0VGHN6jqQRmxS9RKZ5KR3g2QdN8Wu8M2mgYVpwC+6pmJGQCqXgOwXDybAf4RpvQ2B3DnddrMVcBMdN/Da/EQUgr/ubFMaxwMm89yex/aWR7ypt6vUp8OQjc9ke1eLbo37N8RWgMnEyijG3rfHuBkNcr7Vzjq3SIk5mMFSwSoXMEKPfKA+OGv6Lp/0xTlMoSp4h00G1BiDRfMr3yuZLrZUUkijIkPoMgHL4w+U1ykJVJyYpuT1URDAWLr+oyrrETcmbDb8xFvW6qXDMH/vPkX3CQb+G7wCScIBQj02h8T7S+AI63WQ1KhcLWYbA0mV0seg2msZK3vmwzlyF5YbBtWgtZXFJdFx8qLNuJ8S/VR4+diG7F1U1n9OlCJzoGyREdQPFKJXa+1xUXEnpMi1L4adiQ4jrkXsihNj89rBrVkJM7L2OtxhArVQprFlSPE4UPCzKhnkCy37Uf0LkrVGpsZtBSjeQb8juYPznfdbMY6fSssFkRXguZpAFR09fBDE=
  - secure: NP6JRo36nyakgeu11OS7V6hmGAhbmuZSRKPwvgkhX3J0eFL92AbuwyEfd5u3ORIDojN8IPfMf+bigeVr6q1oxe8dBQg6hZ+eiB7bslhmzBVzlugFAcZIHbauyuxLKIsf7W5Br5VeT4eIY7zvrN/Mut8GctZYwQq6CxiZTQgbuChi5NqQHARMGxpF+6S+dGz2MHriKfKN2TXquVS2I/bsQMDmM5srmiuUuz44pZt2p/6iVkYeej3ccCaStbE6lfSR1+HLCSm4Qz3soPRBbf3trAfyd8DWRlJ0mQdPf2wj4VL1d7yFTAeTsYP5CDU5rHnrn1n/RNTlShKyky/6EtxcTr9Y6HHI5hyvxRjE0wv7q1oTpbp8w7/2+4oiWb9Gz5mUIOek+5eRm+F3UMkOGuDQlEtloLDKXHrhzuQBNWOVbPEBc9XnXsePT2wJ9REaXyhjAqnjmlHE2q9B4Cxkf6OH7ewKYqo1PynUGHyvJho58frBIg9X0T3n4oMgrhHAzjnJOiO2tS9Ano1tJMTannwHuJMIL9Eha3jAgBTNFvETfs2pXtQvjQNCIptavmVbvL3pkaMNA06NuP7wGjohgEgWrAvtOofDq3qS8tWL4A2LaiaUGakY3ltpvUiSd573ZVgGHC529Y8hRICZtFY3fM65N8daZsqnyg+7mk8m95pk3D4=
  - secure: DTTzhkfOyGNskrOp4Ythhvzz3YRDrvV+snyPKE6XKWQpEGHzTQ+7psU6H5T5TkKubXAAhVEpsH7l49IrDdmqLG/mFQZ4uzvqdVA1xvyCJpuJK/TCtEgsnhxxIVe40+vJVcCFtUs4i58eQjWeJ7wzOEOMaG0904Wz17BPfCwP4ebfEZlSLKjxYO4Aoser4WDhj2p/pMLw5kn+1ax6lpGlayRmByX8zG+WbIuwC+X2lbdU+5fo+A3APOh6B9a/qt1Xq9azFK1ZEVsscEWtrDfXT1bS8r7yHOmj4vN7BLD/mTTDBx4lP5epTEuZ1yjy/J9QlhT2zaecdmja/XOHRd4Xa2Q+96Z4MdoHuTmiLio0yfGCn3aJ2NeWK5rbyaNmGxvpCGDedzesGAbXL6wa40ox88aRNqUdjsMdUVmvIEvpuxCRsGx0/KS35grYfcaSSOfGkC2lyD+wWwZHVOXssv9P9KarS4XK8C44IxEnIU3t2qTYihRRf1byJfKeTSmZqy9BxATCXikNgghKqHtnoe4mCY5berxdDvbkuxWHcCk5uDRJQu+FI8iZv4jBkShfjEJpkOdLU5/WV9Yl7jJNelx2/o6qyU5gY73vVBTa+XTSMDiE/rsLg/E7P6Dq4u/g0+qIMktRUH+TuW4OBeg+FEMvSqHpQWQIaYq9ulbxzL6ZQXM=
