language: java
jdk: oraclejdk8
os: linux
dist: trusty
services:
- docker
before_install:
- chmod +x mvnw
- curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec
- sudo apt-get -y install ruby ruby-dev gcc g++ make
- ./mvnw clean install -B
after_success:
- echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
- docker build  -t bvassignment .
- docker tag bvassignment $DOCKER_USERNAME/bvassignment:latest
- docker run -d -it -p 8080:8080 $DOCKER_USERNAME/bvassignment:latest
- inspec exec test.rb --chef-license=accept ; export CHECKRESULT=$?
- if [ $CHECKRESULT -eq 0 ];then docker push $DOCKER_USERNAME/bvassignment:latest; else echo "Scan failed!";exit -1; fi
notificaions:
  email:
    recipients:
    - r3ap3rpy@gmail.com
    on_success: always
    on_failure: always